export enum Collections {
  TOURNAMENT = "tournaments",
  GAME_RESTRICTIONS = "game_restrictions",
  GAME_SUMMARY = "game_summaries",
  VENUE = "venues",
  COURT = "courts",
  TEAMS = "teams",
  PLAYERS = "players",
  DIVISIONS = "divisions",
  COACHES = "coaches",
  QUICK_TOURNAMENT = "quick_tournaments",
  TOURNAMENT_CONFIG = "tournament_config",
  LEAGUE = "leagues",
  TOURNAMENT_TIMELINES = "timelines",
  TIMELINE_TASKS = "timeline_tasks",
  BRACKETS = "brackets",
  POOLS = "pools",
  GAMES = "games",
  STAFFS = "staffs",
}
